%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 560
distortion_parameters:
   k1: -5.0040485799999999e-02
   k2: 1.2001217170000000e-01
   p1: -6.2598060000000004e-04
   p2: -1.1825064000000000e-03
projection_parameters:
   fx: 8.1640221474060002e+02
   fy: 8.1738388562809996e+02
   cx: 6.0882658427579997e+02
   cy: 2.6668865652440002e+02
